var SettingL =
[
    {
        "img":"./img/arrow/L10.png",
        "W":108,
        "H":36,
    },
    {
        "img":"./img/arrow/L10-2.png",
        "W":206,
        "H":36,
    },
    {
        "img":"./img/arrow/L10-3.png",
        "W":304,
        "H":36,
    },
    {
        "img":"./img/arrow/L10-4.png",
        "W":402,
        "H":36,
    },
    {
        "img":"./img/arrow/L10-5.png",
        "W":500,
        "H":36,
    },
    {
        "img":"./img/arrow/L10-6.png",
        "W":598,
        "H":36,
    },
    {
        "img":"./img/arrow/L10-7.png",
        "W":696,
        "H":36,
    },
    {
        "img":"./img/arrow/L10-8.png",
        "W":794,
        "H":36,
    },
    {
        "img":"./img/arrow/L10-9.png",
        "W":892,
        "H":36,
    },
    {
        "img":"./img/arrow/L10-10.png",
        "W":990,
        "H":36,
    },
    {
        "img":"./img/arrow/L10-11.png",
        "W":1088,
        "H":36,
    },
    {
        "img":"./img/arrow/L10-12.png",
        "W":1186,
        "H":36,
    },
    {
        "img":"./img/arrow/L10-13.png",
        "W":1284,
        "H":36,
    },
    {
        "img":"./img/arrow/L10-14.png",
        "W":1382,
        "H":36,
    },
    {
        "img":"./img/arrow/L10-15.png",
        "W":1481,
        "H":36,
    },
]
var SettingR =
[
    {
        "img":"./img/arrow/R10.png",
        "W":108,
        "H":49,
    },
    {
        "img":"./img/arrow/R10-2.png",
        "W":206,
        "H":49,
    },
    {
        "img":"./img/arrow/R10-3.png",
        "W":304,
        "H":49,
    },
    {
        "img":"./img/arrow/R10-4.png",
        "W":402,
        "H":49,
    },
    {
        "img":"./img/arrow/R10-5.png",
        "W":500,
        "H":49,
    },
    {
        "img":"./img/arrow/R10-6.png",
        "W":598,
        "H":49,
    },
    {
        "img":"./img/arrow/R10-7.png",
        "W":696,
        "H":49,
    },
    {
        "img":"./img/arrow/R10-8.png",
        "W":794,
        "H":49,
    },
    {
        "img":"./img/arrow/R10-9.png",
        "W":891,
        "H":49,
    },
    {
        "img":"./img/arrow/R10-10.png",
        "W":990,
        "H":49,
    },
    {
        "img":"./img/arrow/R10-11.png",
        "W":1088,
        "H":49,
    },
    {
        "img":"./img/arrow/R10-12.png",
        "W":1186,
        "H":49,
    },
    {
        "img":"./img/arrow/R10-13.png",
        "W":1284,
        "H":49,
    },
    {
        "img":"./img/arrow/R10-14.png",
        "W":1382,
        "H":49,
    },
    {
        "img":"./img/arrow/R10-15.png",
        "W":1481,
        "H":49,
    },
]
var SettingDescription =["./img/window/window01.png","./img/window/window02.png","./img/window/window03.png","./img/window/window04.png"]



